FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

COPY init-namenode.sh /init-namenode.sh
RUN chmod +x /init-namenode.sh

# CMD ["/init-namenode.sh"]

# Run the script
RUN chmod +x /init-namenode.sh
