FROM bde2020/hive:2.3.2-postgresql-metastore

# Copy the initialization script
COPY init-hive.sh /docker-entrypoint-initdb.d/init-hive.sh

# Run the script
RUN chmod +x /docker-entrypoint-initdb.d/init-hive.sh

# Copy the custom configuration files
COPY hive-site.xml /opt/hive/conf/hive-site.xml