version: '3.8'
services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop-config/core-site.xml:/etc/hadoop/core-site.xml   # Aggiunta del montaggio per core-site.xml
      - ./hadoop-config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./hadoop-config/core-site.xml:/etc/hadoop/core-site.xml   # Aggiunta del montaggio per core-site.xml
      - ./hadoop-config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop

  hive:
    build:
      context: .
      dockerfile: Dockerfile.hive
    container_name: hive
    environment:
      - HIVE_SITE_CONF_D=/opt/hive/conf 
    ports:
      - "9083:9083"
    volumes:
      - warehouse:/user/hive/warehouse
      - ./data:/opt/hive/data
      - ./hadoop-config/core-site.xml:/etc/hadoop/core-site.xml   # Aggiunta del montaggio per core-site.xml
    networks:
      - hadoop
    depends_on:
      - hadoop-namenode
      - hadoop-datanode
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:
  warehouse:
  pgdata:

networks:
  hadoop:
