version: '3.8'

services:
  namenode:
    build: ./namenode
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop/conf/core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
      - ./hadoop/conf/hdfs-site.xml:/opt/hadoop-2.7.4/etc/hadoop/hdfs-site.xml
      - ./hadoop/conf/yarn-site.xml:/opt/hadoop-2.7.4/etc/hadoop/yarn-site.xml
    networks:
      - hadoop_network

  datanode:
    build: ./datanode
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./hadoop/conf/core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
      - ./hadoop/conf/hdfs-site.xml:/opt/hadoop-2.7.4/etc/hadoop/hdfs-site.xml
      - ./hadoop/conf/yarn-site.xml:/opt/hadoop-2.7.4/etc/hadoop/yarn-site.xml
    networks:
      - hadoop_network

  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
    ports:
      - "8088:8088"
    volumes:
      - ./hadoop/conf/core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
      - ./hadoop/conf/hdfs-site.xml:/opt/hadoop-2.7.4/etc/hadoop/hdfs-site.xml
      - ./hadoop/conf/yarn-site.xml:/opt/hadoop-2.7.4/etc/hadoop/yarn-site.xml
    networks:
      - hadoop_network

  nodemanager:
    build: ./nodemanager
    container_name: nodemanager
    depends_on:
      - resourcemanager
    ports:
      - "8042:8042"
    volumes:
      - ./hadoop/conf/core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
      - ./hadoop/conf/hdfs-site.xml:/opt/hadoop-2.7.4/etc/hadoop/hdfs-site.xml
      - ./hadoop/conf/yarn-site.xml:/opt/hadoop-2.7.4/etc/hadoop/yarn-site.xml
    networks:
      - hadoop_network

  postgres-hive:
    build: ./postgresql
    container_name: postgres-hive
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hadoop_network

  hive-metastore:
    build: ./hive-metastore
    container_name: hive-metastore
    depends_on:
      - postgres-hive
      - namenode
    ports:
      - "9083:9083"
    volumes:
      - ./hive/conf:/opt/hive/conf
      - ./hive/lib:/opt/hive/lib
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      - hadoop_network

  hive-server:
    build: ./hive-server
    container_name: hive-server
    depends_on:
      - hive-metastore
      - namenode
    ports:
      - "10000:10000"
    volumes:
      - ./hive/conf:/opt/hive/conf
      - ./hive/lib:/opt/hive/lib
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      - hadoop_network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  pgdata:

networks:
  hadoop_network:
    driver: bridge
